# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Theory meets practice...
email: hoehle@su <figure out the rest>
description: > # this means to ignore newlines until "baseurl:"
  A blog about statistics in theory and practice. Not always serious, not always flawless, but definitely a statistically flavoured bean.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: m_hoehle
github_username:  hoehleatsu

# Build settings
markdown: kramdown
